# Generated by Django 5.2 on 2025-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('tipo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('qr', 'QR'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10)),
                ('tipo_entrega', models.CharField(choices=[('delivery', 'Delivery'), ('tienda', 'Recoger en tienda')], default='tienda', max_length=10)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
