# Generated by Django 5.2 on 2025-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('tienda', 'Recoger en tienda')], default='tienda', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('qr', 'QR'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10),
        ),
    ]
