# Generated by Django 5.2 on 2025-04-27 11:10

import storage_backend.azure_sas_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('telefonos', 'Teléfonos y Smartphones'), ('laptops', 'Laptops y Notebooks'), ('tablets', 'Tablets'), ('acc_movil', 'Accesorios para Móviles'), ('acc_pc', 'Accesorios para Computadoras'), ('auriculares', 'Auriculares y Audífonos'), ('camaras', 'Cámaras y Fotografía'), ('wearables', 'Smartwatches y Wearables'), ('consolas', 'Consolas y Videojuegos'), ('tv', 'Televisores y Pantallas'), ('audio', 'Audio y Sonido'), ('drones', 'Drones'), ('almacenamiento', 'Almacenamiento'), ('impresoras', 'Impresoras y Escáneres'), ('redes', 'Routers y Redes'), ('componentes', 'Componentes de PC'), ('electro_inteligente', 'Electrodomésticos Inteligentes'), ('monitores', 'Monitores'), ('proyectores', 'Proyectores'), ('cargadores', 'Cargadores y Baterías'), ('perifericos', 'Periféricos'), ('hogar_smart', 'Hogar Inteligente'), ('powerbank', 'Power Banks'), ('software', 'Software y Licencias'), ('cables', 'Cables y Adaptadores')], default='telefonos', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(storage=storage_backend.azure_sas_storage.AzureMediaStorage(), upload_to='productos/'),
        ),
    ]
